name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Lint
        run: npm run lint
        working-directory: ./app

      - name: Test
        run: npm run test
        working-directory: ./app

      - name: Build
        run: npm run build
        working-directory: ./app
